version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: barcode_inventory
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network
    restart: unless-stopped
  
  ai-server:
    build: ./ai_server
    ports:
      - "5001:5001"
    networks:
      - app_network
  
  webapp:
    build: ./webapp
    ports:
      - "5000:5000"
    networks:
      - app_network
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: barcode_inventory
    depends_on:
      - db

volumes:
  db_data:
  
networks:
  app_network:
