version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mySQL/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  ai_server:
    build: ./ai
    ports:
      - "5001:5001"
    volumes:
      - ./ai/model:/app/model
    networks:
      - app-network

  webapp:
    build: ./webapp
    ports:
      - "5002:80"  # Port 80 inside container exposed to 5002 on host
    networks:
      - app-network
    depends_on:
      - db

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
