version: '3'
services:
  webapp:
    build: ./webapp
    ports:
      - "5000:5000"
    networks:
      - app_network
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: barcode_inventory
    depends_on:
      - db

networks:
  app_network:
    external: true
